/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Metricas;
import javax.swing.JFrame;

/**
 *
 * @author mathe
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        
        //jLabelEscNave1.setLocation(0,0);
        //jLabelEscNave2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        jButtonMenuIniciar = new javax.swing.JButton();
        jLabelTituloJogo = new javax.swing.JLabel();
        jLabelNave1 = new javax.swing.JLabel();
        jLabelNave2 = new javax.swing.JLabel();
        jLabelEscNave1 = new javax.swing.JLabel();
        jLabelEscNave2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asteroids Menu");
        setBounds(new java.awt.Rectangle(0, 0, 625, 417));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/IconGame.png")).getImage());
        setResizable(false);

        jPanelMenu.setBackground(new java.awt.Color(81, 33, 105));

        jButtonMenuIniciar.setBackground(new java.awt.Color(153, 153, 153));
        jButtonMenuIniciar.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jButtonMenuIniciar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMenuIniciar.setText("INICIAR");
        jButtonMenuIniciar.setPreferredSize(new java.awt.Dimension(100, 23));
        jButtonMenuIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuIniciarActionPerformed(evt);
            }
        });

        jLabelTituloJogo.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabelTituloJogo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloJogo.setText("ASTEROIDES");

        jLabelNave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuNave3.png"))); // NOI18N

        jLabelNave2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuNave2.png"))); // NOI18N

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabelNave1)
                .addGap(56, 56, 56)
                .addComponent(jButtonMenuIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabelNave2)
                .addGap(47, 47, 47))
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabelTituloJogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelTituloJogo)
                .addGap(146, 146, 146)
                .addComponent(jButtonMenuIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNave2)
                    .addComponent(jLabelNave1))
                .addGap(36, 36, 36))
        );

        jLabelEscNave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuNave3.png"))); // NOI18N
        jLabelEscNave1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEscNave1MouseClicked(evt);
            }
        });

        jLabelEscNave2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuNave2.png"))); // NOI18N
        jLabelEscNave2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEscNave2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelEscNave1)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelEscNave2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelEscNave1)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelEscNave2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuIniciarActionPerformed
        // TODO add your handling code here:
       
        jPanelMenu.remove(jButtonMenuIniciar);
        jLabelTituloJogo.setText("Escolha sua Nave!");
        
        jLabelEscNave1.setVisible(true);
        jLabelEscNave1.setLocation(jLabelNave1.getX(), jLabelNave1.getY());
        jPanelMenu.remove(jLabelNave1);
        jPanelMenu.add(jLabelEscNave1);
               
        jLabelEscNave2.setVisible(true);
        jLabelEscNave2.setLocation(jLabelNave2.getX(), jLabelNave2.getY());
        jPanelMenu.remove(jLabelNave2);
        jPanelMenu.add(jLabelEscNave2);
                
        jButtonMenuIniciar.setVisible(false);
        
/*
        telaEscNave();
        telaFase1();
*/
    }//GEN-LAST:event_jButtonMenuIniciarActionPerformed

    private void jLabelEscNave1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEscNave1MouseClicked
        // TODO add your handling code here:
        System.out.println("Nave 1 escolhida");
        Metricas.escNave = 1;
        
        telaFase1();
    }//GEN-LAST:event_jLabelEscNave1MouseClicked

    private void jLabelEscNave2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEscNave2MouseClicked
        // TODO add your handling code here:
        System.out.println("Nave 2 escolhida");
        Metricas.escNave = 2;
        
        telaFase1();
    }//GEN-LAST:event_jLabelEscNave2MouseClicked
    
    public void telaEscNave() {
        JFrame escNave = new EscNave();
        escNave.setLocationRelativeTo(null);
        escNave.setVisible(true);
        // fecha o menu
        dispose();
    }
    
    public void telaFase1() {
        JFrame fase1 = new Fase1();
        fase1.setLocationRelativeTo(null);
        fase1.setVisible(true);
        // fecha o menu
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMenuIniciar;
    private javax.swing.JLabel jLabelEscNave1;
    private javax.swing.JLabel jLabelEscNave2;
    private javax.swing.JLabel jLabelNave1;
    private javax.swing.JLabel jLabelNave2;
    private javax.swing.JLabel jLabelTituloJogo;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
